Add wrappable parameter behavior to mouse drag and keyboard up/down
mcslee/GLX pull request #7
Opened 2022-03-15 22:19 UTC by jkbelcher

Pairs with the current mft pull request on LX.

2022-03-15 22:38 UTC, jkbelcher commented on src/main/java/heronarts/glx/ui/component/UISwitch.java
> +    this.keyEditable = true;
Did this to allow up/down keys on UISwitch but can't tell if it will have unintended consequences.

2022-03-16 16:32 UTC, mcslee requested changes
Just some minor changes - main ones are to kill those while loops by using modular arithmetic.

2022-03-16 16:32 UTC, mcslee commented on src/main/java/heronarts/glx/ui/component/UIKnob.java
> +        while (this.dragValue < 0) {
```
if (this.dragValue < 0) {
  this.dragValue = 1 + (this.dragValue % 1.);
} else if (this.dragValue > 1) {
  this.dragValue = this.dragValue % 1.;
}
```

2022-03-16 16:32 UTC, mcslee commented on src/main/java/heronarts/glx/ui/component/UIParameterControl.java
> +      return parameter.isWrappable();
`this.parameter`

2022-03-16 16:32 UTC, mcslee commented on src/main/java/heronarts/glx/ui/component/UIParameterControl.java
> +          value += 1;
Probably never relevant unless something is really wrong with getIncrement()... but just in case.
`value = 1 + (value % 1.)`

2022-03-16 16:32 UTC, mcslee commented on src/main/java/heronarts/glx/ui/component/UIParameterControl.java
> +          value -= 1;
`value = value % 1.`

2022-03-16 16:32 UTC, mcslee commented on src/main/java/heronarts/glx/ui/component/UISwitch.java
> +    this.keyEditable = true;
I think it should be fine, seems reasonable to have here.

2022-03-17 14:28 UTC, jkbelcher commented on src/main/java/heronarts/glx/ui/component/UIKnob.java
> +        while (this.dragValue < 0) {
Changed.  We've done this a couple times now... could consider adding a utility method if we get more instances.  Something like:
public double LXUtils.wrapNormalized(double value) -> value can be outside range of 0-1
or
static default public double LXNormalizedParameter.wrapNormalized(double value)

2022-03-17 14:29 UTC, jkbelcher commented on src/main/java/heronarts/glx/ui/component/UIParameterControl.java
> +      return parameter.isWrappable();
Done

2022-03-17 14:31 UTC, jkbelcher commented on src/main/java/heronarts/glx/ui/component/UIParameterControl.java
> +          value += 1;
Nice, got it.

2022-03-17 14:32 UTC, jkbelcher commented on src/main/java/heronarts/glx/ui/component/UIParameterControl.java
> +          value -= 1;
Done

2022-03-17 18:00 UTC, jkbelcher commented
Ready for review.

2022-03-18 04:04 UTC, mcslee commented on src/main/java/heronarts/glx/ui/component/UIKnob.java
> +        while (this.dragValue < 0) {
Added helpers, can use these in the future: https://github.com/heronarts/LX/commit/80d107cc1e9aa0a8aea4ba49fbcac3577a6f775e

2022-03-18 04:04 UTC, merged